language: r
sudo: false
cache: packages
r:
  - 3.1
  - 3.2
  - oldrel
  - release
  - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'devtools::install_github("jimhester/covr")' -e 'covr::codecov()'
